org: thoughtspring
app: thoughtspring-api
service: thoughtspring-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    environment: 
      SAMPLE_API_KEY: ${param:SAMPLE_API_KEY}
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-plugin-typescript
